### ISSUE TITLE
Python Poetry

### ISSUE THREAD

**Issue by dark0dave** [grrttedwards/wow-addon-updater#107]
Hi @grrttedwards, its me. As you may or may not know pipenv has ceased development. The last supported version of python with pipenv is 3.7~. If you'd like to take advantage of later versions of python 3.8+, my advice is to migrate to [poetry](https://github.com/python-poetry/poetry). Its quite similar to pipenv. Its up to you.

**Comment by torkus** [comment]
> As you may or may not know pipenv has ceased development

`[citation required]`

**Comment by grrttedwards** [comment]
Oof. Yeah that is a shame, if true...

**Comment by dark0dave** [comment]
https://github.com/pypa/pipenv

Have a look at the commit history. Its slowed down massively.

Have a look at poetry see if you like it. Checkout my pr. Hopefully its ok.

**Comment by dark0dave** [comment]
Up to you what you do next. I got poetry working on your repo.

**Comment by torkus** [comment]
Pipenv is positioned as the next official dependency manager. 

The 'pypa' in 'pypa/pipenv' stands for 'Python Packaging Authority'. They maintain the tooling for Pypi, where we download our Python dependencies from. Pypi recommend using pipenv [in their tutorial on how to manage dependencies](https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies).

I find it a bit slow and heavy myself and the original author is a bit of an egocentric jerk, but it's not going anywhere. The drop in commit activity may simply be a sign of stability + christmas/new year holidays.

**Comment by grrttedwards** [comment]
I’ll take a look at the options and the PR hopefully this weekend, thanks everyone for the commentary.
