### ISSUE TITLE
ElvUI_OptionsUI not extracted

### ISSUE THREAD

**Issue by luukvbaal** [grrttedwards/wow-addon-updater#109]
Hi, I recently switched to using this updater instead of the bloated twitch app, thanks!

One issue I've found is that the `ElvUI_OptionsUI` folder contained in the ElvUI release [zip](https://git.tukui.org/elvui/elvui/tree/v11.371) is not extracted, only the `ElvUI` folder ends up in WoW's addon folder. Hence ending up with an outdated or missing options UI in case of a clean install.

**Comment by luukvbaal** [comment]
I did not read the instructions properly, my bad.

**Comment by grrttedwards** [comment]
I’m happy you figured it out! :) Thanks for stopping by
