### ISSUE TITLE
TukUI Addons Fail to Download

### ISSUE THREAD

**Issue by Audited** [grrttedwards/wow-addon-updater#111]
I'm having a bit of trouble with getting the program to download any addon from TukUI that's not ElvUI. For example, listing [https://git.tukui.org/Azilroka/AddOnSkins/](https://git.tukui.org/Azilroka/AddOnSkins/) in addons.txt and running the program, the add-on isn't listed as one to check for updates or install.

I've pinned it down to what I believe being the problem, the tukui.py site URL seems to have hard-listed as ElvUI's git page.

` class Tukui(AbstractSite):`
`    _URLS = [`
`        'https://git.tukui.org/elvui/'`
`    ]`

Removing `elvui/` from the URL gets it to download properly. There may be a reason it's hard-coded, so I thought I'd raise a ticket rather than a pull request.

Some addons are also not listed in their git repo, but are listed on the main website, so it makes it difficult to get them updated. Some repos also house both the classic and retail versions of add-ons in one, so it makes it difficult to separate them (there's also no common folder structure).

I did notice that an add-on through their main website, [https://www.tukui.org/classic-addons.php?id=2](https://www.tukui.org/classic-addons.php?id=2), has an extras tab which contains version information:

![image](https://user-images.githubusercontent.com/4626782/75103806-12ff4580-563b-11ea-893e-d14226f8b823.png)

I can look into the possibility of using this as version information, allowing more add-ons to be installed and updated.

**Comment by grrttedwards** [comment]
Hello! Sorry, been busy. I did read your post here.

I'm finding less time to develop new features for this project nowadays, but let me mull it over for a bit and see if I can help.

**Comment by Audited** [comment]
No problem, I'm new to Python but want to help. I'll try and get something together.

**Comment by grrttedwards** [comment]
Incorporated in #139 
and https://github.com/grrttedwards/wow-addon-updater/releases/tag/v1.7.0

Thank you @Audited !!!
