### ISSUE TITLE
Failed to find addon version number again

### ISSUE THREAD

**Issue by Swatto86** [grrttedwards/wow-addon-updater#117]
Hi all, 
Sorry me again, just tried to use the script and got the same message as before, tried to do a pipenv update to upgrade the dependencies but did not make a difference:

Failed to find addon version number for game version: GameVersion.retail, 
Name                       Prev. Version              New Version                
────                       ─────────────              ───────────                
garrison-mission-manager   -----                      Unavailable

**Comment by grrttedwards** [comment]
Oh no! Ok part of what I worked on last was actually logging! Can you attach the log file that should be generated, or copy paste it here?

**Comment by Swatto86** [comment]
Here you go: https://pastebin.com/f8peb6QQ

dropped connections --> cloudflare updated again?

:)

**Comment by Shizato** [comment]
That's exactly what my log looks like too.

**Comment by grrttedwards** [comment]
Yeah doesn’t look like there is much we can do about it until maybe the cloudscraper folks release a new version.

**Comment by Swatto86** [comment]
They have released a new version of cloudscraper, pipenv update should do the trick.

**Comment by grrttedwards** [comment]
Hey that’s great to hear. I’ll make a release as soon as I can. I also realized I left the thread number out of the log formatter, which was a mistake in my last release.
