### ISSUE TITLE
Github Downloads need to change folder names

### ISSUE THREAD

**Issue by issueaccpost2** [grrttedwards/wow-addon-updater#119]
is there a way to name the folders myself ? addons need specific names for their folders and i cant seem to find a way to rename them without doing that myself manually.

**Comment by grrttedwards** [comment]
No, not at the moment. The support for folder extraction is very brittle in its current form. You could write a script to do the renaming for you automatically, and just pipeline the two commands together?

**Comment by issueaccpost2** [comment]
thanks for the fast response, gonna script something myself for a few addons, would be a nice addition to the updater though
