### ISSUE TITLE
Curse addons: Failed to find addon version number for game version

### ISSUE THREAD

**Issue by rousseauxy** [grrttedwards/wow-addon-updater#120]
Same issue from 10 days ago has come back again :(
_pipenv update_ doesn't seem to help

Failed to find addon version number for game version: GameVersion.retail,
Name Prev. Version New Version

_pipenv run pip freeze_ shows following
beautifulsoup4==4.8.2
certifi==2019.11.28
chardet==3.0.4
cloudscraper==1.2.28
idna==2.9
requests==2.23.0
requests-toolbelt==0.9.1
soupsieve==2.0
urllib3==1.25.8

However, when i go to https://pypi.org/project/cloudscraper/ it should be version 1.2.30
Running _pipenv update cloudscraper_ seemed to be the solution

**Comment by DarkVirtue** [comment]
That fixed it for me as well.

**Comment by grrttedwards** [comment]
I can release an upgrade today, thanks for the heads up. It’s such a silly
game of cat and mouse with this.

**Comment by rousseauxy** [comment]
No problem :)
I was however under the impression that running _pipenv update_ would update those dependancies, or am I wrong?

**Comment by grrttedwards** [comment]
Yes it will, if you do it manually then there is no need to necessarily
update what I publish.
