### ISSUE TITLE
IS this working anymore?

### ISSUE THREAD

**Issue by Mayo77** [grrttedwards/wow-addon-updater#123]
Mine seems to be broken for the past week.. i tried to update it and still seems broken.. sigh. Is this working or do i need to try and go through the 900 steps over agian to get this working. 

Also is there an automatic updater for this yet? I read comments and said they are thinking about adding it but i have no idea how to use it if it actually has this.

Thanks

UPDATE: I got it working . Thanks everyone that contacted me. took a bit but got it.

**Comment by grrttedwards** [comment]
Well, I’m not exactly sure how to answer this issue. I don’t own Curse and can’t control whether or not their CDN makes a breaking change to this script.

Also I’m a little confused by who you’re referring to that helped you, but I’m glad you’ve got it working again. I don’t see any replies here. Are there specific steps you took that helped?

**Comment by Mayo77** [comment]
Not sure what happened but i reinstalled with the newest version and it worked. I bet I made a mistake installing the newest python in windows. This seems to be the common problem i run into most the time , when i am installing this. 

Any which way i did figure it out in the end, by following the guide.

Also i was reading somewhere you guys were talking about making a auto - updater for this program. I would just love to vote "PLEASE do" if its possible. I love this updater when its running but when its broken or if i have to update it I stress out, as I try to avoid to have to update it as i find the entire reinstall a bit much for a novice/non programmer. Its fairly complex, mostly from scratch.

An automatic update the program itself from cmd prompt or something would be great ( maybe there is one, but i never seen it mentioned in the guide if there is one)

But overall thank you for keeping this up to date.

If you dont or cant do any of my suggestions its cool. I can figure it out either way but, overall for me, It would just be nicer and if that was automated.

Anyways thanks again, glad its working again! I hate it when its not working lol.

**Comment by grrttedwards** [comment]
Oh, you definitely shouldn’t have to reinstall Python every time you want to take an update here. You should only have to copy the files into the existing directory and allow it to overwrite everything except any custom configuration files you have.

After that, it should work after _maybe_ needing to update the dependencies which can be done with the `pipenv update` command. I guess I should document that, huh.

**Comment by Mayo77** [comment]
yeah that would be great im super happy you can do it this way.. thats new to me!

**Comment by grrttedwards** [comment]
Oh hunny.
