### ISSUE TITLE
I love it when it working, i hate it when its not.

### ISSUE THREAD

**Issue by Mayo77** [grrttedwards/wow-addon-updater#126]
Listen first off i wanted to say thanks for this addon i really do love it when its working. The problem is The second I have to update this entire process i hate it with a passion. Its so hard to know what i need to do to get it working again. i tried copy and pasting (like you told me to do) and nope that didnt work .. said i was missing requests addon or something. i updated that and now other stuff is broken..

 I always end up having to reinstall this entire addon from scratch.. yes scratch. I'm talking i remove python and everything...i absolutlery HATE it when i see "update available" after i check my wow addons.As i know i may have to go through this entire painfull process yet agian.

 SO please for the love of god add an "update" section on your, guide. I have no idea how to do this without reistalling the entire thing., even after i "tried" what you said to do last time.

Also why isn't a command so i can just update it without having to copy a paste it all? just tired of having to re-install this entire thing every week or so due to "updates", just to have to do agian a week later.

**Comment by Mayo77** [comment]
so thats your help a big thumbs down nice.

**Comment by Mayo77** [comment]
For an average person this install (mostly from scratch) is pretty complex mostly with all the cmd prompt work involved just to get it up and running.... and yet you have no section in your "installation guide" on how to update it once you have it working, without having to go through the entire re-install. 

I understand this is probably basic knowledge to you but to a standard person it is not at all. 

like why can i go into cmd prompt and type something like

-update grrttedwards program

and it would automatically update all the proper files for me, so i dont have to reinstall python for the 50th time.

Sorry but im just frustrated to have to do this every single update, im not a programmer.

**Comment by grrttedwards** [comment]
I'm sorry for your trouble using this, but please know I maintain this code as a hobby. If it doesn't work for you, there are other alternatives (not including the Curse client) which may be easier to use.

https://ogri-la.github.io/wow-addon-managers/

This user maintains a great list of the aforementioned alternatives.

**Comment by Mayo77** [comment]
Yeah i get there are crappier ones out there that come bundled with bloatware, and i understand you are doing this for free. Im really not trying to shit on this, I just am confused on why its such a pain the ass to update.

I just wish you could make the entire process a bit easier for "regular" people. For programmers im sure this install is breeze.

I am actually pretty decent on computers compaired to many people i know and i still struggle with keeping this updater ...updated. I could only imagine how this would be for people that are not decent... they would probably just grab one of those curse clients bloatware and use it, i guess.

In the end I will get it working agian( i always do), its just like pulling teeth after every update... it will take me some time but i will get python and all the rest reinstalled. 

But i still think you should just make an cmd prompt updater, would save so much frustration.

**Comment by Audited** [comment]
You can use `pipenv update` to update the dependencies.

Generally the affected one is cloudscraper, a Python module to bypass the anti-bot page for sites protected by Cloudflare (an anti-bot-bot?).

When there's a new version of this module, it's generally because Cloudflare has updated their anti-bot techniques.

I'll submit a PR to add documentation on how to update the dependencies.
