### ISSUE TITLE
Getting "Failed to find addon version number for game version" when downloading from Curse

### ISSUE THREAD

**Issue by SteveWiFi** [grrttedwards/wow-addon-updater#128]
Hello!

This issue has reared its head over the past week. I thought it might be a temporary thing with Curse, but I now think they've made changes to the layout of their site which causes the issue.

>Failed to find addon version number for game version: GameVersion.classic, https://www.curseforge.com/wow/addons/rclootcouncil-classic
>Failed to find addon version number for game version: GameVersion.classic, https://www.curseforge.com/wow/addons/prat-3-0
>Failed to find addon version number for game version: GameVersion.classic, https://www.curseforge.com/wow/addons/pally-power
>Failed to find addon version number for game version: GameVersion.classic, https://www.curseforge.com/wow/addons/details-damage-meter-classic-wow

**Comment by Ghosthree3** [comment]
Every time this happens run `pipenv update` in the directory (where you ran the initial setup), usually it either solves the problem or will in the next few days. Currently mine is still working after doing it a few days ago.

**Comment by SteveWiFi** [comment]
Thanks! This resolved my issue.
