### ISSUE TITLE
Failed to find version number...downloading issue

### ISSUE THREAD

**Issue by Swatto86** [grrttedwards/wow-addon-updater#129]
Good Morning,

I hope you are all doing well in these exceptional times.  I've just tried to use the wow-addon-updater to update my addons from curseforge but it is failing as above.

I have tried 'pipenv update' which I believe updated some bits but it still fails.

Any chance you can take a look please when you have time.

Thanks very much
[addon-updater.log](https://github.com/grrttedwards/wow-addon-updater/files/4485680/addon-updater.log)

**Comment by Mayo77** [comment]
Just wanted to verify I am having the exact same issue. Same issue. Also tried "pipenv update" and still broke. 

Thanks for all the hard work.

**Comment by Switchxa** [comment]
Same issue. Tried the update as well. Running newest version.

**Comment by grrttedwards** [comment]
I will take a look, it’s unfortunately out of my hands and we rely on the owners of the cfscraper module to determine how to bypass the issue.

**Comment by SveSop** [comment]
I think there are ppl on the case. Might be related: [https://github.com/VeNoMouS/cloudscraper/issues/185](https://github.com/VeNoMouS/cloudscraper/issues/185)

**Comment by esnar11** [comment]
using the fix fspy gave at https://github.com/grrttedwards/wow-addon-updater/issues/99 to change session to your own browsers user agent worked for me.

**Comment by Swatto86** [comment]
> using the fix fspy gave at #99 to change session to your own browsers user agent worked for me.

Worked for me too - very strange

**Comment by grrttedwards** [comment]
Looking for some guinea pigs to try out a patch. Might have found the dumbest solution possible to this issue. I have a feeling that cloudflare goes and finds any "big lists of useragents" it can find to render those lists invalid. After all, those are the kind of lists that the people who cause real trouble scraping the web might use.

https://github.com/grrttedwards/wow-addon-updater/commit/663b077021b39de30a2b2132c7d4056bf4f4beab

Depending on how this goes, we might have just gotten lucky, or I might start looking for some way to allow you to pass in your own useragent string.

**Comment by icyblade** [comment]
A dirty workaround is to fill the challenge in browser first, and apply the cookie in browser to the code.

Basically we need to do:
```python
HEADERS = {
    'User-Agent': 'blahblah',  # UserAgent from browser request
    'Cookie': 'blahblah',  # Cookie from browser request
}
Curse.session.get(self.url, headers=HEADERS)
```
Every time we access the site protected by cloudflare.

**Comment by grrttedwards** [comment]
Took a shot at fixing out of the box in #139 
and https://github.com/grrttedwards/wow-addon-updater/releases/tag/v1.7.0
