### ISSUE TITLE
Version file not updated

### ISSUE THREAD

**Issue by olepg** [grrttedwards/wow-addon-updater#130]
In the latest version of 1.6.4, the version file still says "1.6.3", so I get a update message every time I run it.

Furthermore, it was difficult figuring out which version I had. I recommend adding a text somewhere displaying what version I'm running. For example: "You're running v1.6.3, a new update (v1.6.4) is available! Check it out at..."

**Comment by grrttedwards** [comment]
Well, that’s embarrassing! Haha. I’ll take a look at either republishing it or fixing the other issues people have posted and releasing a new correctly tagged version.

Also will add more information to the “upgrade available” message.
Thanks, sorry that notice is probably annoying.

**Comment by grrttedwards** [comment]
Fixed in #139 
and https://github.com/grrttedwards/wow-addon-updater/releases/tag/v1.7.0
