### ISSUE TITLE
Tukui/Elvui Download broken

### ISSUE THREAD

**Issue by yaccin** [grrttedwards/wow-addon-updater#140]
**Describe the bug**
Since the switch from github to the "new and improved" elvui/tukui downloads it doesn't work anymore. The problem is that, while it might work for classic wow, the links for the retail version are completely different and will not work with the new version. However, the old github links also no longer work. Clearly a regression.

**If you run `pipenv update` on the command line and try again, does the issue go away?**
No

**Comment by grrttedwards** [comment]
Agh. Sorry. I took that PR without having tested it myself... 

Would you be okay if it worked for the main download page for classic and retail? Or do you prefer going to the tukui git repository?

**Comment by yaccin** [comment]
Either would work fine :) thanks for the quick reply! :)

**Comment by grrttedwards** [comment]
I haven't added a sponsor button to the repo, but if you'd like you can find me at https://paypal.me/garrettedwards 

That's very generous of you!

**Comment by grrttedwards** [comment]
Hey @yaccin if you wouldn't mind, please try out what's in #141 

This should add back support for elvui/tukui regardless of the game version you're targeting.

Apologies for the regression in the first place.

**Comment by yaccin** [comment]
I would love to test it, but my git knowledge is a bit... rudimentary at best :D if you can tell me how i can apply the changes from #141 temporarily i might be able to help :)

**Comment by grrttedwards** [comment]
It's just one file, and you probably don't have git installed, so just copy and paste the contents of this:

https://raw.githubusercontent.com/grrttedwards/wow-addon-updater/2b51466cab60685047c28c35c379630c63b928fd/updater/site/tukui.py

into the file `tukui.py` in the updater/site folder, and then run the tool normally with whatever tukui/elvui addons you want

**Comment by yaccin** [comment]
I have tested it and it is working! Thanks for the quick fix :)

**Comment by grrttedwards** [comment]
Cool, I’ll publish the changes to the tests I made and get a release out
soon. Thanks!
