### ISSUE TITLE
addon updates on wowinterface.com not detected

### ISSUE THREAD

**Issue by StevenSlater** [grrttedwards/wow-addon-updater#143]
the topic says it all, addons configured with a wowinterface.com url seem to have quietly stopped updating (a few months ago). maybe because the version number is no longer displayed on the main addon page there?
no error message or anything, the updater just reports all such addons as up-to-date
e.g.:
https://wowinterface.com/downloads/info8814-DeadlyBossMods.html
DeadlyBossMods                               8.2.20                                       Up to date                                   

i generally prefer wowinterface over curse for addons available on both because their downloads don't break due to cloudflare updates every couple of weeks... but if such a bug can go unnoticed for months, i might have to reconsider :(

**Comment by grrttedwards** [comment]
If you have other examples of addons that "quietly stopped updating" please give them.

> but if such a bug can go unnoticed for months, i might have to reconsider :(

Not sure what you mean by this, it's not really a bug. The download button on the DeadlyBossMods page gives you version 8.2.20.zip. The maintainers of DeadlyBossMods need to use wowinterface correctly.

**Comment by StevenSlater** [comment]
i see... it actually looks like there's something wonky about the way DBM is hosted on wowinterface.com:
- DBM's current version is 8.[b]3[/b].20, that is also the version i'd get from curse and/or the latest release on DBM's github page. (the wowinterface page does also have 8.3.20, but only listed under "files".)
- wowinterface incorrectly still lists 8.[b]2[/b].20 as the "current" version. that's also what i'd get from the download button there. that version is from january, there have been quite a lot of releases since.
so i guess the updater does everything right, it's the wowinterface maintainers of DBM who are to blame... sorry for the bother.

**Comment by grrttedwards** [comment]
Yeah, I would honestly love to fix this if it were a predictable problem, but they just don’t use wow interface correctly 🤦 

Maybe try opening an issue on their github, they are pretty active there.

Thanks!
