### ISSUE TITLE
Error: No module named updater.

### ISSUE THREAD

**Issue by Khayla** [grrttedwards/wow-addon-updater#144]
I have followed all the steps to install but I'm getting an error when I try to run the bat file.

C:\Users\NAME\.virtualenvs\System32-eU24dAeB\Scripts\python.exe: No module named updater

Any idea what's going on here?

**Comment by grrttedwards** [comment]
Hi! Hmm not sure if I’ve ever seen this particular issue. When you ran the commands to set up the environment, were you in the same directory as the batch file you’re trying to use?

In other words, the terminal you used should have been “in” the directory containing this project code. 

```
C:\Users\Name>cd wow-addon-updater
C:\Users\Name\wow-addon-updater>pipenv install
```

**Comment by Khayla** [comment]
Sure did and there is a folder named updater in there.

I've installed it in Program Files so I'm having to run everything as an admin. Will this have messed anything up?

**Comment by grrttedwards** [comment]
Yeah I would try doing it outside a directory that requires elevated permissions. Let me know how it goes.

**Comment by grrttedwards** [comment]
Feel free to reopen for more support
