### ISSUE TITLE
Spesific addon not updating

### ISSUE THREAD

**Issue by olepg** [grrttedwards/wow-addon-updater#146]
Hi

Even though this addon is no longer being updated, this script doesn't seem to download the latest version regardless. So I'm posting this in case it uncovers a potential bug.

https://www.curseforge.com/wow/addons/tankwarningsclassic

returns: 
"Failed to find addon version number for game version: GameVersion.classic, https://www.curseforge.com/wow/addons/tankwarningsclassic"

**Comment by grrttedwards** [comment]
Hi @olepg 

Unfortunately that’s a limitation right now with Curse addons that are in “alpha” or “beta” and haven’t been fully released. Another user just encountered this in #145 , so maybe I should think about it.

**Comment by grrttedwards** [comment]
Hi, opened #149 for tracking this
