### ISSUE TITLE
alpha/beta addon versions.

### ISSUE THREAD

**Issue by ghostkill3r** [grrttedwards/wow-addon-updater#147]
if i done a bad in writing here, please delete my question,

but a way to update to an alpha or beta.. or update a already installed alpha/beta version would be a nice addition to an already nice script/updater.
your script is a really nice to have, especially with curse being sold to overwolf :/

anyways, thanks for the updater/script <3

**Comment by grrttedwards** [comment]
Nah it's a decent request, you're the third request in about a month for this that I keep hand-waving due to how much I hate working with Curse. #146 #145 

I'll think about this, but no promises 😛

**Comment by sucht** [comment]
sorry for my english, but don't stress it (or is it me stressing?) hmm :)

anyways, thank you for considering it, even if it means working with curse <3
i would have a look myself but i really have no clue about python, java and all that other HTML stuff needed for this :(

**Comment by ghostkill3r** [comment]
sorry for my english, but don't stress it (or is it me stressing?) hmm :)

anyways, thank you for considering it, even if it means working with curse <3
i would have a look myself but i really have no clue about python, java and all that other HTML stuff needed for this :(

oh and i always use and install beta and sometimes alpha versions, because i hope something breaks and i can pretend to learn a bit or two ... lua code and all that.
that's why i wrote the "don't stress it", it's just a thing i have fun with ... going through code and try to learn. :/

**Comment by grrttedwards** [comment]
Hi, opened #149 for tracking this
