### ISSUE TITLE
GitHub lingust reports html as primary language of project

### ISSUE THREAD

**Issue by amas0** [grrttedwards/wow-addon-updater#155]
Adding the static Curse parsing test resource to the repo threw off what GitHub is reporting as the primary language and shows HTML as the largest proportion of code base instead of Python.

A quick search leads me to believe this can be resolved with modifying a `.gitattributes` file to exclude the testing files.

**Comment by grrttedwards** [comment]
Nice spot, looks like this is the way to configure Github's language stat collector:
https://github.com/github/linguist#overrides

**Comment by amas0** [comment]
Looks like it worked!
