### ISSUE TITLE
Can you support some proxy setting?

### ISSUE THREAD

**Issue by aweftr** [grrttedwards/wow-addon-updater#161]
For the **elvui**, I can access it directly and the updater works fine. But I have to use proxy to access curseforge addons, so can you add some proxy setting in this updater, such as `wow-addon-updater.exe --proxy <proxy>`?
Thanks.

**Comment by grrttedwards** [comment]
Hi @aweftr , interesting that you have to use a proxy. Could you attach or paste your latest log here so I could see what's going on? It's a file called `addon-updater.log`

Proxy support should be easy, it's also possible it could already be supported/enabled via environment variables.

**Comment by grrttedwards** [comment]
Check out https://requests.readthedocs.io/en/master/user/advanced/#proxies
Under the hood, this project is using the requests module. You should be able to set your proxy like the following:
```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```
and your requests will be routed through the proxy you specify.

You can include credentials like `"http://user:pass@10.10.1.10:3128/"`

**Comment by aweftr** [comment]
I am using conda to manage my python environment. And this is my environment setting:
```
(pytorch) PS F:\game\wow-addon-updater> pip list | findstr "request | beautiful | cloudscraper"
beautifulsoup4                    4.9.3
cloudscraper                      1.2.48
requests                          2.22.0
requests-oauthlib                 1.3.0
requests-toolbelt                 0.9.1
(pytorch) PS F:\game\wow-addon-updater> python -V
Python 3.7.6
(pytorch) PS F:\game\wow-addon-updater> $env:http_proxy
http://localhost:2802
(pytorch) PS F:\game\wow-addon-updater> $env:https_proxy
http://localhost:2802
```
I can install elvui, but it seems that Curse may be blocking my requests. I can access curseforge in chrome through proxy.
Here is my log: [addon-updater.log](https://github.com/grrttedwards/wow-addon-updater/files/5358402/addon-updater.log)

**Comment by grrttedwards** [comment]
So, after setting your environment HTTP/S proxy variables, it still does not work for you? The log is very odd to me, especially how it rewrote your URLs to include what I assume is the cloudflare browser check.
If I set my proxy environment variables, it uses my proxy for all requests as I expected, I cannot reproduce this problem :(

**Comment by aweftr** [comment]
Oh, I change my proxy server to a US server and the updater runs smoothly. But for the previous server, I do not know why I can access curseforge in chrome but the updater produce this odd log.
Thanks for your help :)
