### ISSUE TITLE
Curse returning Internal Server Error when fetching addons - updater fails with 'Failed to find addon version number'

### ISSUE THREAD

**Issue by Ghosthree3** [grrttedwards/wow-addon-updater#176]
**Describe the bug**
I ran the previous build directly before updating to 1.8.1 (and thus learned about the new update) and everything worked fine, after updating almost none of my addons will update (only non curseforge ones). I've looked at the commits that make up the release and honestly cannot figure out how curseforge was even affected.

**If you run `pipenv update` on the command line and try again, does the issue go away?**
No, also tried deleting the virtualenv, upgrading python to the latest release (3.9.4) then trying to `pipenv install` from scratch.

**Log output**
Here's an example of one of the traceback errors (every failed addon has this).
```
[ERROR] [7784] [updater.manager.addon_manager] Failed to find addon version number for game version: GameVersion.retail, https://www.curseforge.com/wow/addons/details
Traceback (most recent call last):
  File "G:\wow-addon-updater-master\updater\site\curse.py", line 101, in versions
    _, *version_rows = versions_table.find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\wow-addon-updater-master\updater\manager\addon_manager.py", line 100, in update_addon
    latest_version = site.get_latest_version()
  File "G:\wow-addon-updater-master\updater\site\curse.py", line 126, in get_latest_version
    return self.latest_release().name
  File "G:\wow-addon-updater-master\updater\site\curse.py", line 113, in latest_release
    latest = next(version for version in self.versions() if version.type >= self.addon_version)
  File "G:\wow-addon-updater-master\updater\site\curse.py", line 113, in <genexpr>
    latest = next(version for version in self.versions() if version.type >= self.addon_version)
  File "G:\wow-addon-updater-master\updater\site\curse.py", line 110, in versions
    raise self.version_error() from e
updater.site.abstract_site.SiteError: Failed to find addon version number for game version: GameVersion.retail, https://www.curseforge.com/wow/addons/details
```

**Comment by grrttedwards** [comment]
I love curse

**Comment by grrttedwards** [comment]
I have a feeling this is just due to their website being broken. Can you hit this page? Or do you get an error?
https://www.curseforge.com/wow/addons/details/files/all

I see the following after some time in my browser:

```
Internal Server Error
An internal server error has occurred. Please try again later. If the error continues please reach out to support.
```

**Comment by Ghosthree3** [comment]
No, I get the same error after waiting 30 seconds for it to load. So weird that I updated successfully (or I thought as much) a mere 5-10 minutes before trying the updated version.
That page is hyperlinked on the /files page so perhaps it'll just get fixed, if it isn't in a few days or a week maybe a workaround is needed but I guess it wasn't the fault of this program (gotta love curseforge).

**Comment by RavenDT** [comment]
I was having this issue on two versions older as well.  I updated to 1.8.1 and didn't fix the issue.  I also updated to latest version of Cloudscraper and made sure BS4 was up-to-date as well.

**Comment by omicron-o** [comment]
The page you linked loads fine for me currently (didn't try before) and I can update my addons as well.

**Comment by grrttedwards** [comment]
@omicron-o thanks for checking!

The automated tests passed this morning, and it looks like they fixed that broken page, so I think we are in the clear!

Happy updating, everyone.

**Comment by omicron-o** [comment]
If the broken page actually responded with a 5xx error I suppose that could be caught and more cleanly reported instead of just the generic can't find version number, giving more of a hint to the user that the problem may be on the addon source website rather than in the updater.
