### ISSUE TITLE
[REQUEST] Add TBC Game Version

### ISSUE THREAD

**Issue by jazminite** [grrttedwards/wow-addon-updater#177]
Pre-patch is launching today and the TBC version of addons will be needed if you move your character to TBC.

Please add TBC option for downloading addons.

Example addon on Curse with TBC version:
https://www.curseforge.com/wow/addons/bartender4

**Comment by Ghosthree3** [comment]
As a very quick band-aid until real support is added, change the 5 numbers after the : on line 90 of updater/site/curse.py from `67408` to `73246`.
At least this appears to have worked for me.
Not all addons have a BC release yet so you'll get some failures.

**Comment by grrttedwards** [comment]
I love seeing the activity around this issue, everyone!

looks like #178 this user has taken a shot at it.

I think we are going to see a big mess over the next few days/weeks as the addon sites all need to have support added for tbc, and unfortunately I am working off an iPad right now so I may have a hard time making the changes.

**Comment by przano** [comment]
> As a very quick band-aid until real support is added, change the 5 numbers after the `:` on line 90 of `updater/site/curse.py` from `67408` to `73246`.
> At least this appears to have worked for me.
> Not all addons have a BC release yet so you'll get some failures.

Good find Ghost. I'm a noob programming nerd, so wanted to ask how you found the new 73246 value?

**Comment by grrttedwards** [comment]
Hey all, 1.9.0 is out there now. Thanks again!

**Comment by Ghosthree3** [comment]
> Good find Ghost. I'm a noob programming nerd, so wanted to ask how you found the new 73246 value?

I just found the old number then checked the page source on curseforge and looked for a similar value close by to it in the same setup for BC.

**Comment by jazminite** [comment]
Thanks everyone! It's working for me 🎉
