### ISSUE TITLE
curse.py:versions() ignores GameVersion.classic enum

### ISSUE THREAD

**Issue by cr0ok** [grrttedwards/wow-addon-updater#180]
**Describe the bug**
Choosing 'classic' in the config.ini downloads "tbc" addons for _classic_era_ instead of the expected "classic" versions.

**If you run `pipenv update` on the command line and try again, does the issue go away?**
No

Simple change in curse.py line 91, changing 'if' to 'elif' resolved the issue.

**Comment by grrttedwards** [comment]
Thank you! v1.9.1 published including your changes
