### ISSUE TITLE
Curseforge addons not updating

### ISSUE THREAD

**Issue by davidmacdonald80** [grrttedwards/wow-addon-updater#192]
First thank you for this and the time you put into it!  
Addons on curseforge aren't being pulled.  From everything I read, there may not be anything to do but wait for now.  WowACE, wowinterface, github, and tukui seem to be fine and updating like they are supposed to.

**If you run `pipenv update` on the command line and try again, does the issue go away?**
Yes, ran 'pipenv update' and no change.  

**Log output**
[addon-updater.log](https://github.com/grrttedwards/wow-addon-updater/files/7720223/addon-updater.log)
[curseforge-unittest.log](https://github.com/grrttedwards/wow-addon-updater/files/7720230/curseforge-unittest.log)

**Comment by grrttedwards** [comment]
Hey there. You are correct, Curse and their CDN often block this tool, and there's not a whole lot we can do except for rewrite it, which I don't have the time for anymore :(

So unfortunately just wait it out for now and see if it resolves itself.
