### ISSUE TITLE
Github releases support as bandaid for curse blocking downloads

### ISSUE THREAD

**Issue by omicron-o** [grrttedwards/wow-addon-updater#199]
Many addons have tagged releases on github in addition to the releases on curse. I've extended the code to support downloading these releases from github.

Due to editor configuration my local version has been partially reformatted by [black](https://github.com/psf/black) so I would have to pick out the changes without reformatting the entire files if I want to submit a pull request. Are you still interested in taking pull requests like that now that you no longer play the game or should I just not bother?

**Comment by grrttedwards** [comment]
Via #200 
released in [v1.10.0](https://github.com/grrttedwards/wow-addon-updater/releases/tag/v1.10.0) 

Thanks @omicron-o
