### ISSUE TITLE
Module not found error addon_manager.py - requests

### ISSUE THREAD

**Issue by sdjohnson72** [grrttedwards/wow-addon-updater#204]
Error: 
  File "/home/shane/Downloads/wow-addon-updater-master/updater/manager/addon_manager.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Python version : Python 3.11.0

Just started occurring after upgrading Fedora to 37.  requests is installed.
![image](https://user-images.githubusercontent.com/40698703/205081523-75e21976-5869-4652-aae0-e1c8b75dd1d6.png)

**Comment by grrttedwards** [comment]
Hello. I'm not sure what your system looks like. You install python packages with your system package manager? Can you just try to `import requests` in the python REPL?

```
PS > python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.__name__
'requests'
>>>
```

If you don't manage your packages globally with pip or use pipenv, I can't really help out here

try
```
python -m pip install requests
```
 and then running the updater again

**Comment by sdjohnson72** [comment]
That works; it's only when running the script to update the addons that the
error about the import pops up.

Shane

**Comment by grrttedwards** [comment]
How are you invoking the script?

**Comment by sdjohnson72** [comment]
./run_MacLinux.sh

**Comment by grrttedwards** [comment]
You aren't using your local python installation if you're using one of the scripts to run the updater. You'd be using a pipenv managed environment which doesn't have requests..
Run
```
pipenv install
```
like the README says.

**Comment by sdjohnson72** [comment]
this is what I get from that:
***@***.*** wow-addon-updater-master]$ pipenv install
/usr/lib/python3.11/site-packages/pipenv/vendor/attr/_make.py:876:
RuntimeWarning: Running interpreter doesn't sufficiently support code
object introspection.  Some features like bare super() or accessing
__class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
Installing dependencies from Pipfile.lock (f35ca8)...
An error occurred while installing beautifulsoup4==4.9.3
--hash=sha256:fff47e031e34ec82bf17e00da8f592fe7de69aeea38be00523c04623c04fb666
--hash=sha256:4c98143716ef1cb40bf7f39a8e3eec8f8b009509e74904ba3a7b315431577e35
--hash=sha256:84729e322ad1d5b4d25f805bfa05b902dd96450f43842c4e99067d5e1369eb25!
Will try again.
An error occurred while installing certifi==2021.5.30
--hash=sha256:2bbf76fd432960138b3ef6dda3dde0544f27cbf8546c458e60baf371917ba9ee
--hash=sha256:50b1e4f8446b06f41be7dd6338db18e0990601dce795c2b1686458aa7e8fa7d8!
Will try again.
An error occurred while installing chardet==4.0.0
--hash=sha256:0d6f53a15db4120f2b08c94f11e7d93d2c911ee118b6b30a04ec3ee8310179fa
--hash=sha256:f864054d66fd9118f2e67044ac8981a54775ec5b67aed0441892edb553d21da5!
Will try again.
An error occurred while installing cloudscraper==1.2.58
--hash=sha256:dda29028c5628b5ba3e4dc43816ed38fd46bd945ef938c420f185586a6d8dff2
--hash=sha256:674fd739f9412188aae8d6614e3e6316939fc0670ef5646abd3d316f1a59d3c2!
Will try again.
An error occurred while installing idna==2.10
--hash=sha256:b97d804b1e9b523befed77c48dacec60e6dcb0b5391d57af6a65a312a90648c0
--hash=sha256:b307872f855b18632ce0c21c5e45be78c0ea7ae4c15c828c20788b26921eb3f6!
Will try again.
An error occurred while installing pyparsing==2.4.7
--hash=sha256:c203ec8783bf771a155b207279b9bccb8dea02d8f0c9e5f8ead507bc3246ecc1
--hash=sha256:ef9d7589ef3c200abe66653d3f1ab1033c3c419ae9b9bdb1240a85b024efc88b!
Will try again.
An error occurred while installing requests==2.25.1
--hash=sha256:27973dd4a904a4f13b263a19c866c13b92a39ed1c964655f025f3f8d3d75b804
--hash=sha256:c210084e36a42ae6b9219e00e48287def368a26d03a048ddad7bfee44f75871e!
Will try again.
An error occurred while installing requests-toolbelt==0.9.1
--hash=sha256:968089d4584ad4ad7c171454f0a5c6dac23971e9472521ea3b6d49d610aa6fc0
--hash=sha256:380606e1d10dc85c3bd47bf5a6095f815ec007be7a8b69c878507068df059e6f!
Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 10/10 — 00:00:00
An error occurred while installing soupsieve==2.2.1; python_version >=
'3.0'
--hash=sha256:c2c1c2d44f158cdbddab7824a9af8c4f83c76b1e23e049479aa432feb6c4c23b
--hash=sha256:052774848f448cf19c7e959adf5566904d525f33a3f8b6ba6f6f8f26ec7de0cc!
Will try again.
An error occurred while installing urllib3==1.26.5
--hash=sha256:753a0374df26658f99d826cfe40394a686d05985786d946fbe4165b5148f5a7c
--hash=sha256:a7acd0977125325f516bda9735fa7142b909a8d01e8b2e4c8108d0984e6e0098!
Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]:
/home/shane/.local/share/virtualenvs/wow-addon-updater-master-hmgucSne/bin/python:
No module named pip
ERROR: Couldn't install package: beautifulsoup4
 Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 7/10 — 00:00:00
/usr/lib64/python3.11/subprocess.py:1123: ResourceWarning: subprocess 3217
is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=4 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=7 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib64/python3.11/subprocess.py:1123: ResourceWarning: subprocess 3218
is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=6 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=9 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib64/python3.11/subprocess.py:1123: ResourceWarning: subprocess 3219
is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=8 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=11 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib64/python3.11/subprocess.py:1123: ResourceWarning: subprocess 3220
is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=10 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=13 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib64/python3.11/subprocess.py:1123: ResourceWarning: subprocess 3221
is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=12 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=15 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib64/python3.11/subprocess.py:1123: ResourceWarning: subprocess 3222
is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=14 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=17 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib64/python3.11/subprocess.py:1123: ResourceWarning: subprocess 3223
is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=16 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=19 mode='rb'
closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback

Thank you
Shane

**Comment by sdjohnson72** [comment]
This still errors out with pipenv install and pipenv python -m updater.  Any suggestions?  Please let me know if you need any further information regarding this issue.
