### ISSUE TITLE
Updater doesn't differentiate between retail and classic addons

### ISSUE THREAD

**Issue by Ghosthree3** [grrttedwards/wow-addon-updater#30]
Some addons are releasing classic versions of themselves under the same project as their retail versions causing issues when it comes to pulling the most recent update (file).

Example: https://www.curseforge.com/wow/addons/weakauras-2
Currently pulls 2.14.0-beta5-7-g73dc607-classic when what's really wanted is the retail release, 2.14.0-beta5-7-g73dc607.
Another example: https://www.curseforge.com/wow/addons/big-wigs
Pulls v2-classic when we actually want v163.

Possible fix:
Add config.ini option 'Game Version', which takes a single number. When the /files page is checked for the latest version name, if the first character in its matching Game Version column does not match that of the config, the next line in the table should be checked. (It may be easier to use the /files/all page).
In this example, 'Game Version' should be set as 8 or 1, making a match with 8.2.0 or 1.13.2 respectively. The whole version should not be required as it is both unnecessary and could cause problems when new patches are released.
This should also help with classic addons support (copy the directory and change the config and addons list).

Though another issue, I'm not sure why weakauras-2 is getting its latest release from the top of the /all page https://www.curseforge.com/wow/addons/weakauras-2/files/all but big-wigs is getting its from the top of the non /all page https://www.curseforge.com/wow/addons/big-wigs/files (latest release on /all is v163-4-gff0f762).

Another suggestion related to both issues, consider adding an option 'Release Type' which does something similar to my fix mentioned above, except for the Type column which contains one of three letters, R, B or A. Personally I'd rather just get the latest Release, and not bother updating to new Alpha versions like 2.14.0-beta5-7-g73dc607.

**Comment by grrttedwards** [comment]
@Ghosthree3 Thanks. Hey, you're the one who inspired this fork! Thank you!

Oof. That's a good one. Makes me want to have more tests!
Can you list all of the ones that are giving you issues, just so we have a running list that can be tested?

**Comment by grrttedwards** [comment]
If we look down on the bottom right, we can actually see these two sections. I think this may be a better approach to take a look into.

![image](https://user-images.githubusercontent.com/5453928/63060995-caafdf80-bec1-11e9-8152-5cdb73bf850e.png)

I checked a few addons, looks like most that have stable classic versions have entries there. Something like Weakauras actually does not have a classic release version, and does not have an entry in that lower-right.

![image](https://user-images.githubusercontent.com/5453928/63061073-fd59d800-bec1-11e9-9cc1-8b87ef9f30c2.png)

**Comment by grrttedwards** [comment]
@Ghosthree3 I've made a change to the way that the versions are grabbed for curse addons. I didn't see the behavior you were talking about for weakauras, but there was definitely a problem with the reported bigwigs version.
