### ISSUE TITLE
Github addons installed into addons folder as -master

### ISSUE THREAD

**Issue by kalimaz0** [grrttedwards/wow-addon-updater#47]
Had this in the addons.txt:
https://github.com/project-classic/ClassicCodex
Installs into World of Warcraft/_classic_/Interface/AddOns/ as ClassicCodex-master instead of ClassicCodex.
Any ideas?

**Comment by grrttedwards** [comment]
Hi @kalimaz0, does this break the installation? Another contributor
actually added the github integration, but let me take a look and get back
to you.

You basically just need it to extract to the folder AddonName, and not
AddonName-master, right?

**Comment by kalimaz0** [comment]
This stops addons from working when downloading from github, yeah just needs AddonName instead of AddonName-master.

**Comment by grrttedwards** [comment]
@kalimaz0 Thank you for reporting! :) 

This should be fixed by #48, and is now in master. Let me know if you have any other problems.
