### ISSUE TITLE
ElvUI version fetching doesn't match downloaded version

### ISSUE THREAD

**Issue by Ghosthree3** [grrttedwards/wow-addon-updater#52]
Currently ElvUI is being updated with:
`return self.url + '/-/archive/master/elvui-master.zip'`
(where self.url is https://git.tukui.org/elvui/elvui)
This is good, as we always get a stable release from the _master_ branch.

But the version fetched and stored during the update is the hash from the development branch, because it's the default branch shown at https://git.tukui.org/elvui/elvui

This causes two problems:
The version is incorrect (I false reported a bug that had already been fixed to the ElvUI team once because of this).
We get 'fake' updates caused by the latest development commit changing, but the master zip staying the same. (The same zip is downloaded and extracted, changing nothing but wasting time/bandwidth).

Recommended fix:
You could instead pull the commit hash from https://git.tukui.org/elvui/elvui/tree/master but I don't recommend this. Instead I would use the latest tag from https://git.tukui.org/elvui/elvui/-/tags which seems to always match the latest commit in the master branch anyway, but is more clear to the end user when it comes to telling them what version of the addon they just installed.

Side note, the classic version is https://git.tukui.org/elvui/elvui-classic and should work with the existing code, other than find_zip_url which would need to be changed (...elvui-classic-master.zip).

**Comment by grrttedwards** [comment]
@Ghosthree3 I just opened #54 , which should fix the issue you were seeing (thanks for the tip on the tags page!). I'm bringing in BeautifulSoup with this change, so going forwards it will hopefully be more stable, and finding what we want will be easier.

This also now supports the classic elvui! Thanks again.

Keep up the awesome reporting, and I'll try to keep up with you.
