### ISSUE TITLE
Curse addons with only classic version fails to download

### ISSUE THREAD

**Issue by grrttedwards** [grrttedwards/wow-addon-updater#53]
An addon with a classic-only version like https://www.curseforge.com/wow/addons/libclassicdurations will not download in classic mode.

**Comment by guppy42** [comment]
Not sure if it's related but this one
https://www.curseforge.com/wow/addons/classicthreatmeter

get completely ignored when I add it to addon.txt

**Comment by grrttedwards** [comment]
If it only has one version, then unfortunately the code is broken for that
right now in classic mode. There are so many configurations on Curse that
the addon owners can upload with, so this is on my todo list to figure out.

I’m not sure why the addon owners don’t just upload using the “classic”
version tag on the same page as the retail version!

I did figure out a workaround, but it makes a bad assumption and will
incorrectly install classic addons to a retail game version if classic is
the only option on the page. It’s better than nothing, though.

I just brought in a better html parser, so I will see if I can get a better
extraction of the version for addons and fix this/avoid the caveat I just
mentioned.

**Comment by guppy42** [comment]
> I’m not sure why the addon owners don’t just upload using the “classic”
version tag on the same page as the retail version!

To be fair some of those addons only exists for classic.

This workaround you speak off, can I pull it anywhere? I only play classic so I don't mind a bad hack that doesn't work with retail ;)

**Comment by grrttedwards** [comment]
Sure, when I get home today I can push my branch, and I’ll let you know.

**Comment by grrttedwards** [comment]
@guppy42 @MercyMyWaifu

Since you both liked that post, here's a tag.

Take a peek at #55
