### ISSUE TITLE
Assistance with Setup / Install

### ISSUE THREAD

**Issue by Seraphic001** [grrttedwards/wow-addon-updater#56]
Hi There,

I've been used the previous version of this script for a long time, I followed the setup / install instructions correctly I believe, but my Python knowledge is quite limited.

I receive the following error at the end of the process

"Failed to parse configuration file. Are you sure it is formatted correctly?"

Any assistance to point me in the right direction please ?

-----

`C:\Games\Python\wow-addon-updater-master>pip install pipenv
Requirement already satisfied: pipenv in c:\games\python\python37\lib\site-packa
ges (2018.11.26)
Requirement already satisfied: virtualenv in c:\games\python\python37\lib\site-p
ackages (from pipenv) (16.7.4)
Requirement already satisfied: virtualenv-clone>=0.2.5 in c:\games\python\python
37\lib\site-packages (from pipenv) (0.5.3)
Requirement already satisfied: pip>=9.0.1 in c:\games\python\python37\lib\site-p
ackages (from pipenv) (19.2.3)
Requirement already satisfied: certifi in c:\games\python\python37\lib\site-pack
ages (from pipenv) (2019.6.16)
Requirement already satisfied: setuptools>=36.2.1 in c:\games\python\python37\li
b\site-packages (from pipenv) (41.2.0)

C:\Games\Python\wow-addon-updater-master>pipenv install
Creating a virtualenv for this project.
Pipfile: C:\Games\Python\wow-addon-updater-master\Pipfile
Using c:\games\python\python37\python.exe (3.7.3) to create virtualenv.
[=== ] Creating virtual environment...Already using interpreter c:\games\python\
python37\python.exe
Using base prefix 'c:\\games\\python\\python37'
New python executable in C:\Users\Law\\.virtualenvs\wow-addon-updater-master-iaGb
lsuV\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

Successfully created virtual environment!
Virtualenv location: C:\Users\Law\\.virtualenvs\wow-addon-updater-master-iaGblsuV

Installing dependencies from Pipfile.lock (983816).
  ================================ 7/7 - 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

C:\Games\Python\wow-addon-updater-master>pipenv run python -m updater
Failed to parse configuration file. Are you sure it is formatted correctly?

C:\Games\Python\wow-addon-updater-master>`

----

My "config.ini"

`[WOW ADDON UPDATER]
WoW Addon Location = C:\Games\World of Warcraft\_retail_\Interface\AddOnsAddon List File = addons.txt
Installed Versions File = installed.ini
# retail or classic
Game Version = retail`

**Comment by Seraphic001** [comment]
Solved it

Deleted old "installed.ini"

Please close ticket.

Thanks

**Comment by grrttedwards** [comment]
Hi @Seraphic001 ,

Good to know you fixed your issue, thanks for posting!
