### ISSUE TITLE
Noob User

### ISSUE THREAD

**Issue by Sesquipedal** [grrttedwards/wow-addon-updater#59]
Hello good sir -- firstly thank you so much for taking the project over.  You're wonderful for just that in itself.  Now, I hope you can help me (and hopefully others) that come across this.  I don't consider myself completely dumb when it comes to computers, but in this case I think I am in over my head a bit.  I don't code, and until I installed the original updater, I didn't know there was a .py extension.  Please take a moment to help, and maybe update the readme a bit once I am helped, so that others can be helped:

The beginning install seems very convoluted.  

You wrote:

> This utility has two external dependencies:
> 
> The requests module, for making HTTP requests
> The BeautifulSoup4 module, for HTML document parsing
> The install should be managed by pipenv. All you need to do is run the following:
> 
> cd wow-addon-updater/
> pip install pipenv
> pipenv install

So I went to those sites and gathered all the files.  I had to assume you wanted the tar.gz files, and not the wheel versions.  I don't know what those are, I just had to choose.
I put them all in the wow-addon-updater-master folder that I have inside my wow directory. 
I then have assume that I can use a command line (I am a windows 10 user).  

So I went to cmd and cd to wow-addon-updater-master (which I request you change the instructions to that instead of wow-addon-updater as your file structure has the former when directly copied)

I don't want to mix all the files unless I am supposed to do that.
No matter, I cd to the pipenv-master folder I have inside my addon-updater folder, and I try some of those command lines, but to no avail.  It doesn't recognize pip or pipenv as commands.  I guess that makes sense because how can windows know to run a pip command if it is not installed yet, maybe?

Anyway, that's my struggles. 

I have two areas of concern:

1) Where do I go to run 
> cd wow-addon-updater/
> pip install pipenv
> pipenv install

2) after that, will the two dependencies be installed?  Any more steps?  Where do I put the two dependencies?  Into the root wow-addon-updater-master folder?  

After that, I know to change the config to do classic, get the addon list made for it to run, and go from there.  Just this first part is aggravating haha.  

I know you must think I am completely silly for trying to run this without knowing how to install the first part, but maybe this will make it more popular, if we get a bit more detail on the install process.

Thank you kindly either way.

**Comment by Sesquipedal** [comment]
Ah, I assumed I had python already, as I used the original updater extensively.  I think thats why I cant use pip commands.  I'll install that first.

**Comment by Sesquipedal** [comment]
I installed python, and restarted.  cmd couldn't recognize pip commands still, and I tried powershell just in case to no avail as well.

**Comment by MercyMyWaifu** [comment]
C:\Users\youruser\AppData\Local\Programs\Python\Python37-32\Scripts\pip3.exe install pipenv

**Comment by MercyMyWaifu** [comment]
and edit run_Windows.bat
C:\Users\youruser\AppData\Local\Programs\Python\Python37-32\Scripts\pipenv.exe run python -m updater

**Comment by grrttedwards** [comment]
Hi @Sesquipedal, thanks for stopping by!

Let's try to help you out. So, I see the documentation could use a bit more explanation of where `pip` and `pipenv` come from. I'll keep that in mind.

As for what you tried to do in your original post, I think you may have gone down the wrong path here... what my documentation should say is something like:


> You will need to have both `pip` and `pipenv` installed on your system.
>
> You should already have `pip` included with your Python installation, but if not, download the latest version of Python for your platform, with `pip` bundled.
>
> Once you have Python and `pip` set up, you can install `pipenv` by executing:
> ```
> pip install pipenv
> ```
> or
> ```
> python -m pip install pipenv
> ```

To address some of your other concerns:

> So I went to cmd and cd to wow-addon-updater-master (which I request you change the instructions to that instead of wow-addon-updater as your file structure has the former when directly copied)

This is what GitHub happens to name the folder if you download the `master` archive. The instructions are hopefully clear enough to tell someone that they should `cd` to whichever folder name corresponds to what they downloaded.

> I have two areas of concern:
> 1. Where do I go to run

You should run these from within the `wow-addon-updater` directory. For example if you downloaded the master archive, then `cd wow-addon-updater-master` after unzipping it.

> after that, will the two dependencies be installed? Any more steps? Where do I put the two dependencies? Into the root wow-addon-updater-master folder?

This part here is specifically what `pipenv` is for. When you are in the directory containing this code, then executing:

```
pipenv install
```

will take care of installing those external libraries for you.

At that point, then you can use the clickable executable, or if you want you can invoke it directly with the run command:

```
pipenv run python -m updater
```

I hope this was helpful, let me know if you have any other problems.

The comments above from @MercyMyWaifu may be helpful if you're having path problems, but I think what I wrote here should be more straightforward, since you just want to make it simple.

**Comment by grrttedwards** [comment]
I have created #60 with some of what confused you

**Comment by Sesquipedal** [comment]
Thank you so much @MercyMyWaifu and @grrttedwards .  Very helpful.
I sort of did the instructions as I read them, so I did @MercyMyWaifu first.  They worked perfectly to get things started.  I went to the directory and ran run_Windows.bat.
It did a bunch of installing-like things, and asked me to close.
I did, and then tried to run it again to update and addon to test.  Ibefore running I specified my wow folder, that it was classic, and made the addon.txt file with a curseforge link.

When I run it, I now get:

> E:\World of Warcraft\wow-addon-updater-master>C:\Users\Sesquipedal\AppData\Local\Programs\Python\Python37\Scripts\pipenv.exe run python -m updater
> Traceback (most recent call last):
>   File "c:\users\sesquipedal\appdata\local\programs\python\python37\Lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\sesquipedal\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "E:\World of Warcraft\wow-addon-updater-master\updater\__main__.py", line 4, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'
> 
> E:\World of Warcraft\wow-addon-updater-master>PAUSE
> Press any key to continue . . .

How do I rectify this module problem?

**Comment by Sesquipedal** [comment]
Ah and to comment:

> This is what GitHub happens to name the folder if you download the master archive. The instructions are hopefully clear enough to tell someone that they should cd to whichever folder name corresponds to what they downloaded.

That makes sense.  I didn't know there were multiple ways to grab the files off github, and I see that you'd want to make sure the instructions are universal as possible.  Since I was able to figure that part of it out easily I'd agree with you there.

**Comment by Sesquipedal** [comment]
Ah that's one of the dependencies.  Should I be placing that somewhere other than the addon dir?

**Comment by MercyMyWaifu** [comment]
do this, then try to update
C:\Users\Sesquipedal\AppData\Local\Programs\Python\Python37\Scripts\pip.exe install requests

**Comment by grrttedwards** [comment]
@Sesquipedal I wouldn't suggest installing the dependencies with pip, if you follow the instructions to `pip install pipenv`, then continue with the pipenv installation it will be much easier for you.

**Comment by MercyMyWaifu** [comment]
https://imgur.com/sMP09OE
and it’s better to reinstall python, with this checkmark, just to write a command, and not all the way to python

**Comment by Sesquipedal** [comment]
I def didn't check that. Ah maybe that's why the pip command and all that doesn't recognise still.  OK I will reinstall and check that option.  I'll report back.  thank you

**Comment by Sesquipedal** [comment]
That explains it!   Once I reinstalled with the check box, the pip commands that @grrttedwards  were saying now work and are recognized.  I wonder why it doesn't check that by default.  Amazing.  I was so confused that @grrttedwards sounded like I just type it, but it never worked. Now it does!   Maybe that's a good point of the python install to note for new users that don't deal with Python.

So in cmd I did a pipenv install requests
And I reverted the .bat to be pipenv like you had it @grrttedwards 

Still I get the same error however:

> E:\World of Warcraft\wow-addon-updater-master>pipenv run python -m updater
> Traceback (most recent call last):
>   File "c:\users\sesquipedal\appdata\local\programs\python\python37\Lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\sesquipedal\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "E:\World of Warcraft\wow-addon-updater-master\updater\__main__.py", line 4, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'
> 
> E:\World of Warcraft\wow-addon-updater-master>PAUSE
> Press any key to continue . . .

**Comment by grrttedwards** [comment]
Just run `pipenv install`, as stated in the documentation.

**Comment by Sesquipedal** [comment]
Don't worry, I did that long ago.  I did it again just because you wrote it just now, but I still have the same issue.

**Comment by Sesquipedal** [comment]
> C:\Users\Sesquipedal>pipenv install
> Installing dependencies from Pipfile.lock (444a6d)…
>   ================================ 5/5 - 00:00:00
> To activate this project's virtualenv, run pipenv shell.
> Alternatively, run a command inside the virtualenv with pipenv run.
> 
> C:\Users\Sesquipedal>

Just to prove

**Comment by grrttedwards** [comment]
> C:\Users\Sesquipedal>pipenv install

You have to run this command from inside the `wow-addon-updater` directory.

**Comment by MercyMyWaifu** [comment]
Ах вот как это работает. Я requests отдельно устанавливал до этого.

**Comment by Sesquipedal** [comment]
Ah yes, my mistake, hence the cd in your documentation.  In my happiness that the commands you wanted me to run started working, I neglected to go back to the documentation.  Thanks!    The addon test worked perfectly.  

I think in all this, your documentation would work great if that checkbox @MercyMyWaifu mentioend during install was checked.  So I think just by adding that (if you want of course), it would help people like myself.

**Comment by Sesquipedal** [comment]
Also, thanks so much for helping us stay away from bloat ware :)

**Comment by MercyMyWaifu** [comment]
Love @grrttedwards, hate twitch app
