### ISSUE TITLE
Allow both retail and classic addons to be updated from the same instance

### ISSUE THREAD

**Issue by Ghosthree3** [grrttedwards/wow-addon-updater#62]
Enhancement request.

Currently a copy of the program is required to update addons for more than one version of the game, adjusting the 'Game Version' and 'WoW Addon Location' variables.

In order for both versions to be updated simultaneously I suggest some combination of the following changes:
'Game Version' variable removed, or changed to 'Default Game Version'.
'addons.txt' split into two appropriate files, 'addons_retail.txt' and 'addons_classic.txt' (addons.txt could be kept as legacy and use the 'Default Game Version').
Single 'addons.txt' is kept and takes an additional, optional word input (new line format 'URL [retail|classic]', defaults to 'Default Game Version' if not supplied).
'WoW Addon Location' renamed to 'Retail Addon Location' and a second variable, 'Classic Addon Location' added (if either is left blank, appropriate subroutine is skipped).
Variable changed entirely to 'WoW Location' and takes the root directory as its value instead of the addons directory ('\\\_{version}_\Interface\AddOns' easily appended at runtime).

Low priority.

**Comment by grrttedwards** [comment]
I thought about what you're suggesting, but couldn't come up with something I particularly liked. Check out the following, which I recently added:
https://github.com/grrttedwards/wow-addon-updater#multiple-configurations

**Comment by grrttedwards** [comment]
You could edit your `run_Windows.bat` to contain
```
pipenv python -m updater -c config_retail.ini
pipenv python -m updater -c config_classic.ini
```
which is exactly how I'm using it right now.
