### ISSUE TITLE
Can someone please make a step by step on how to install this for people like me that are not programmers.

### ISSUE THREAD

**Issue by Mayo77** [grrttedwards/wow-addon-updater#74]
I tired to follow the install guide but it makes no sense to me.

> "You should already have pip included with your Python installation. This is the default package manager for Python. If not, download the latest version of Python for your platform, with pip bundled.
> 
> This utility has three Python module dependencies:
> 
>     The requests module, for making HTTP requests
>     The BeautifulSoup4 module, for HTML document parsing
>     The cfscrape module, for bypassing Curse's bot-detection measures
> 

First off i have no idea if i even have "pip" installed, because there is no clear direction on how I can check if it is.

Number 2 (from the install guide)

> It's recommended you manage this with pipenv. All you need to do is run the following to install pipenv and the dependencies:
> 
> cd wow-addon-updater/
> pip install pipenv
> pipenv install
> 
> The packages will be automatically installed by pipenv to a local virtual environment"

Now this might make sense if your a programmer but for me, I have literally no idea what I'm supposed to do here... am i supposed to open python or cmd line and type this in ? I have no idea i wish this guide was more clear to people that are not programmers/ regular python users.

**Comment by grrttedwards** [comment]
Hello @Mayo77 

You can check if you have `pip` installed by just typing `pip` in your command prompt/cmd/terminal and seeing what it says. Just `pip` alone is not a full command, but as long as it doesn't say "command not found" or something, then you're good.

If you don't have it, download a new Python installer like it says.

Next, go download Node.js. There is a link in the README. If you saw the other issues regarding Curse, I just pushed a fix for that and unfortunately it now requires Node.js.

Next, you have to open your command prompt again and "`cd`" which means (change directory) to the folder with all the code for this utility. I don't know what platform you're on, but `cd` should work the same way on all platforms that I can think of. Type something like `cd C:\Downloads\wow-addon-updater-v1.2.0` or whatever your path to the folder with the code is.

At this point, then type the next two lines from the instructions
```
pip install pipenv
pipenv install
```

If all that worked, then you shouldn't have to use the command prompt any more.

If there is any configuration you need to do, then edit the `config.ini` file with your changes.

To run, just double click on the `run_Platform.bat/sh` script, and it should do its magic.

**Comment by grrttedwards** [comment]
Side note, you're a good use case for the other issue I have open #14 😺 But, I'm not sure when I'll have time to get that done.

**Comment by Mayo77** [comment]
So I type pip in cmd and i get this;

**Comment by grrttedwards** [comment]
> 'pip" is not recognized

Sounds a lot like "not found". You don't have it installed.

**Comment by Mayo77** [comment]
So i downloaded the newest version available online(3.7.4) and from what i read pip is automatically added. but it still shows exact same error in cmd.

**Comment by grrttedwards** [comment]
Windows can be a pain sometimes and you will have to restart your machine to see it work. Try that first

**Comment by Mayo77** [comment]
same error

**Comment by grrttedwards** [comment]
Did you check the box that says "install pip" when you installed the new version of Python?

**Comment by Mayo77** [comment]
yes

**Comment by Mayo77** [comment]
I installed newest version of python with pip (i checked prior to install)
I open cmd and type this is command: (without quotes)
"pip"

and this is what pops up every single time

> 'pip" is not recognized as an internal or external command. Operable program or batch file.

**Comment by grrttedwards** [comment]
What does the following command print out?
```
echo %PATH%
```

**Comment by Mayo77** [comment]
Its huge. and i cant copy it im on wiondows 7

**Comment by Mayo77** [comment]
c program file x86\intel\icls client\c;program files\intel\icls client\;c;\windows\system32;C;windows.


and it keeps going

**Comment by grrttedwards** [comment]
Well, there's definitely a reason I asked for that, but if it's too big to show me then I'm not sure I can help 😿

**Comment by Mayo77** [comment]
Nevermind i guess this is way to complicated. Ill just use curse.

**Comment by grrttedwards** [comment]
Sorry to hear it's too complicated for you. It looks like you tried to manually type out the output of the last command I asked for. You can also just copy and paste, or take a screenshot. But if you've given up, that's okay too.

I'm not sure why you wrote "RIP wow addon updater", there are plenty of non-"programmer" users who we have helped get the setup steps completed.
