### ISSUE TITLE
Idea: Parameter to supress "xxx version ... is up to date"

### ISSUE THREAD

**Issue by Kiraan75** [grrttedwards/wow-addon-updater#93]
What about adding a "command line parameter" (to be set within the .bat) to supress the output of "xxx version ... is up to date" (i.e. only "relevant" lines - updated addons or errors - will be shown). There's a lot of scrolling, so it would be easier to only catch the interesting actions.

addon_manager.py line 101
print(f"{addon_name} version {installed_version} is up to date.\n")

(Every update of your great code I change this line to "pass" but... you know ;-)

**Comment by grrttedwards** [comment]
For sure, I get tired of seeing those messages too. Somewhat related to this is #41 where I hope I can make the logging and exception handling easier to manage.

**Comment by grrttedwards** [comment]
:)
