### ISSUE TITLE
Make it automatically close on finish?

### ISSUE THREAD

**Issue by IvanDeluxe** [grrttedwards/wow-addon-updater#94]
Sorry, I'm not aware if this already exists or not...

Also, thanks a bunch for this pure awesomeness of a project :)

**Comment by grrttedwards** [comment]
Hi @IvanDeluxe, it shouldn’t actually pause on finish unless you use the clickable executables. If that’s the case, you can edit the file and just remove the last line which says `pause`, and it won’t pause anymore.

Thanks!
