### ISSUE TITLE
Curse is blocking requests, again.

### ISSUE THREAD

**Issue by jaredm4** [grrttedwards/wow-addon-updater#95]
```
PS C:\...\wow-addon-updater-retail> .\run_Windows.bat
Curse is blocking requests because it thinks you are a bot... please try later.
Failed to find addon version number for game version: GameVersion.retail, https://www.curseforge.com/wow/addons/nameplate-scrolling-combat-text
```

Tried updating cfscrape to latest version but didn't help. PeachTree's version using cloudscrape also didn't work.

They're onto us. :(

**Comment by grrttedwards** [comment]
Honestly you’d think they’re running something saving people’s lives... Curse, you’re a file host, calm down!

If an issue doesn’t exist already on cfscrape, it might be a good idea to cross-post there.

**Comment by jaredm4** [comment]
Honestly I blame Twitch. They want every gamer using their PoS client.

**Comment by layday** [comment]
You can tap into the Twitch client's API to bypass all of this anti-spam nonsense.  You can find unofficial documentation for the API [here](https://twitchappapi.docs.apiary.io/).

**Comment by Jicksaw** [comment]
I'm getting this on my Windows 10 system, but not on a 8.1 one. Tried different IPs. First time trying on the Win 10 system so idk if it would have worked before either.

**Comment by grrttedwards** [comment]
@layday Good idea. It doesn't look very easy to use, though. I'll look into it.

@Jicksaw This is affecting everyone right now, probably until there is an update on the cfscrape module used to bypass Cloudflare.

See: 
https://github.com/Anorov/cloudflare-scrape/issues/319
https://github.com/Anorov/cloudflare-scrape/issues/318

And it's hard for me to really tell what this is doing (I'm unfamiliar with this library), but it appears like there is an Open PR which is trying to address a change in the js challenge.
https://github.com/Anorov/cloudflare-scrape/pull/315

**Comment by dark0dave** [comment]
@grrttedwards I have experimented with that branch Anorov/cloudflare-scrape#315, and the news is not good I am afraid.

**Comment by grrttedwards** [comment]
I appreciate you checking it out, it’s been a busy time for me. Unfortunately it doesn’t look like there’s a workaround yet :(

**Comment by grrttedwards** [comment]
Switching to https://github.com/VeNoMouS/cloudscraper is another possible solution, it appears like they’ve released recently to address the new cloudflare challenge.

**Comment by layday** [comment]
The API is fairly trivial to use but the one staggeringly obvious drawback is if you identify add-ons by their URL you'll have to find a way to extract the add-on ID from the URL that does not trigger the CloudFlare interstitial.  The API does not appear to support searching for add-ons by their URL or slug.  What I and some other people have done is to scrape the `/search` endpoint and map slugs to their corresponding IDs - this could be done on a timer from inside `wow-addon-updater` but expect it to take ~30s per run and use a fair bit of bandwidth.  Otherwise you can set up a scraper here on GitHub (e.g. using GitHub Actions) which runs once daily/weekly/biannually.  This does also mean users will be unable to install newly-published add-ons for the time it takes to re-scrape the API 😔

**Comment by grrttedwards** [comment]
https://github.com/grrttedwards/wow-addon-updater/pull/96

I've created this PR which switches to use cloudscraper over cfscrape. This is a breaking change to the installation that requires a `pipenv install` and maybe a `pipenv clean` if you want to remove cfscrape from the environment.

Looks like it's working, though.

@layday that's a good chunk of info, but I think the sad emoji says it all lol

**Comment by layday** [comment]
These add-on hosts truly are a bliss to work with.

**Comment by grrttedwards** [comment]
Hey all, I've published a new version https://github.com/grrttedwards/wow-addon-updater/releases/tag/v1.5.0 which takes advantage of the new module `cloudscraper` mentioned above. Sorry this took so long to get resolved, it's a busy time of year. Thanks for the reports and discussion.

**Comment by olepg** [comment]
I'm still having the same issue after updating to v1.5.0.

**Comment by grrttedwards** [comment]
Ah.. wait, really? It was passing/successfully downloading for me on my local machine as well as on the test server on Travis. 

I just re-ran the master branch build on Travis, and saw the same successful results: https://travis-ci.com/grrttedwards/wow-addon-updater

Can you visit Curse in your browser? @olepg

**Comment by jaredm4** [comment]
Updated to 1.5.0, ran `pipenv install` and `pipenv clean`, got a new error.

> Failed to find addon version number for game version: GameVersion.retail, https://www.curseforge.com/wow/addons/skada

For all curse addons.

**Comment by Laitinenn** [comment]
> Updated to 1.5.0, ran `pipenv install` and `pipenv clean`, got a new error.
> 
> > Failed to find addon version number for game version: GameVersion.retail, https://www.curseforge.com/wow/addons/skada
> 
> For all curse addons.

Same keeps happening for me too.

**Comment by olepg** [comment]
@grrttedwards 
I have no issues using chrome on the website: https://www.curseforge.com/wow/addons/itemrack-classic.
But this is the error message I get:

`Failed to find addon version number for game version: GameVersion.classic, https://www.curseforge.com/wow/addons/itemrack-classic`

**Comment by grrttedwards** [comment]
I wish I had the logging issue completed right around now 😛 

I still can't reproduce this myself, locally or on Travis... which is concerning. Many of you seem to be having issues. What's bad is that it's not the 403 error that Cloudflare gives when it rejects your requests, it's a different exception which is not being logged.

Someone please try this patch:
```diff
diff --git a/updater/site/curse.py b/updater/site/curse.py
index 6fd16a0..deb436f 100644
--- a/updater/site/curse.py
+++ b/updater/site/curse.py
@@ -17,7 +17,7 @@ class Curse(AbstractSite):
         _OLD_PROJECT_URL
     ]
 
-    session = cloudscraper.create_scraper("https://www.curseforge.com/")
+    session = cloudscraper.create_scraper()
 
     def __init__(self, url: str, game_version: GameVersion):
         url = Curse._convert_old_curse_urls(url)
@@ -35,6 +35,8 @@ class Curse(AbstractSite):
             zip_url = classic_zip_url[-1] if self.game_version is GameVersion.classic and classic_zip_url else main_zip_url
             return f'https://www.curseforge.com{zip_url}/file'
         except Exception as e:
+            import traceback
+            traceback.print_exc()
             raise self.download_error() from e
 
     def get_latest_version(self):
```

and report back with what gets printed out, or if you still have issues.

**Comment by jaredm4** [comment]
The patch didn't work, the logging should have been near the line 54 exception instead. Manually made that change, and I got output :)

```Traceback (most recent call last):
RuntimeError: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.```

It looks like maybe we have a missing dependency that didn't make it into the Pipfile.lock?

Here's my list of installed pips.

```PS C:\Users\Jared\Documents\wow-addon-updater-retail> pipenv run pip list
Package           Version
----------------- ----------
beautifulsoup4    4.8.1
Brotli            1.0.7
certifi           2019.11.28
chardet           3.0.4
cloudscraper      1.2.16
idna              2.8
pip               19.2.3
requests          2.22.0
requests-toolbelt 0.9.1
setuptools        41.2.0
soupsieve         1.9.5
urllib3           1.25.7
wheel             0.33.6```

**Comment by jaredm4** [comment]
When I have some time (after holiday) I'll try this branch on the old cfscrape, people there claim it is working. https://github.com/Anorov/cloudflare-scrape/pull/315

**Comment by grrttedwards** [comment]
@jaredm4 Kudos. I’m really puzzled by the reports here, since I’m unable to see it... weird. Please follow up with your results. Maybe we can do a live debug together in the new few days.

**Comment by olepg** [comment]
I tried the changes to curse.py you suggested @grrttedwards. But that just returns an error. 
If there's anything I can do to help you troubleshoot, just tell me what to do.

**Comment by jaredm4** [comment]
I didn't have any luck switching back to cloudscrape using the branch that supposedly fixed it. But I'm also not super familiar with python/pipenv so may have done it wrong. My results:

Switched back to v1.4.2, then set cfscrape to the branch [here](https://github.com/alzamer2/cloudflare-scrape/tree/fix_new_cloudflare_change_30-11-2019). Then ran `pipenv install` and `pipenv clean`.

```PS wow-addon-updater-retail> pipenv run pip list
Package        Version    Location
-------------- ---------- --------------------------------------------------------------------------
rotli         1.0.7
beautifulsoup4 4.8.2
certifi        2019.11.28
cfscrape       2.0.8      c:\...\.virtualenvs\wow-addon-updater-retail-fw_h4kk2\src\cfscrape
chardet        3.0.4
idna           2.8
pip            19.2.3
requests       2.22.0
setuptools     41.2.0
soupsieve      1.9.5
urllib3        1.25.7
wheel          0.33.6
PS wow-addon-updater-retail> pipenv run python -m updater
Curse is blocking requests because it thinks you are a bot... please try later.
Traceback (most recent call last):
  File "C:\...\Documents\wow-addon-updater-retail\updater\site\curse.py", line 47, in get_latest_version
    page.raise_for_status()  # Raise an exception for HTTP errors
  File "C:\...\.virtualenvs\wow-addon-updater-retail-fw_H4kk2\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.curseforge.com/wow/addons/astral-keys
```

Assuming I did that right, bummer.

**Comment by grrttedwards** [comment]
Sorry for my absence the past few weeks. For anyone still having issues, please check out the code in the #100 , which upgrades some dependencies. I didn't have an issue connecting to Curse with this version.
