### ISSUE TITLE
Failed to find addon version number for game version: GameVersion.retail

### ISSUE THREAD

**Issue by DarkVirtue** [grrttedwards/wow-addon-updater#99]
The updater is failing to to get version numbers for all installed addons. Curse may have changed they way they're categorizing addons or something.

**Comment by fspy** [comment]
Actual error:
`Exception has occurred: RuntimeError
Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
  File "redacted\wow-addon-updater\updater\site\curse.py", line 42, in get_latest_version
    page = Curse.session.get(self.url)
  File "redacted\wow-addon-updater\updater\manager\addon_manager.py", line 92, in update_addon
    latest_version = site.get_latest_version()`

Apparently Curse is now using CloudFlare's reCaptcha service to avoid scraping the site.
It might be possible to configure `cloudscraper` to avoid the issue, but as-is, a third-party reCaptcha solver service would be required, and those are paid.

Will attempt to spoof UserAgent and report back.

**Comment by crborga** [comment]
Changing useragent worked for me as well.

**Comment by grrttedwards** [comment]
That's interesting, the way that I saw both the scrapers implemented was that they randomly choose a browser-like useragent from a big list in the source code... so maybe cloudflare has gone and specifically targeted those... that sounds like an absurd amount of effort for them to go through 😞

**Comment by grrttedwards** [comment]
Also interesting to note, I shouldn't be passing in a url string to `create_scraper()` since that is expecting a session object... harmless bug, but whoops.

**Comment by grrttedwards** [comment]
Someone please try out https://github.com/grrttedwards/wow-addon-updater/pull/100, which upgrades the dependencies. I didn't have any issues with Curse on the new dependency versions.

**Comment by crborga** [comment]
Latest master branch works for me after doing pipenv clean and pipenv install.

**Comment by DarkVirtue** [comment]
Works for me, as well.
